version: '2'

services:
  # MySQL container
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: secret

  # Build container
  build:
    build: ./docker/build
    image: ${COMPOSE_PROJECT_NAME}_build

  # App container
  app:
    image: ${COMPOSE_PROJECT_NAME}_build
    links:
      - db
    depends_on:
      - db
      - build
    ports:
      - ${EXTERNAL_HTTP_PORT}80
    volumes:
      - ~/.composer:/.composer
      - ~/.npm:/.npm
      - ~/.cache/bower:/.cache/bower
      - ./:/app
    environment:
      - COMPOSER_HOME=/.composer
      - NPM_CONFIG_CACHE=/.npm
      - BOWER_STORAGE__PACKAGES=/.cache/bower
